Added cucumber test to the docker compose file

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -29,27 +29,30 @@ jobs:
           sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: "20"
-
-      - name: Install dependencies
-        run: npm install
-
-      - name: Run Docker Compose
-        run: docker-compose up --build -d
+      - name: Build and start Docker Compose
+        run: docker-compose -f docker-compose.yml up --build -d
 
       - name: Wait for services to be ready
         run: |
           echo "Waiting for services to be ready..."
-          sleep 10  # Wait for a few seconds to ensure services are up
+          sleep 30  # Wait for a few seconds to ensure services are up
+          continue-on-error: true
 
       - name: Verify Docker Compose status
         run: docker-compose ps
         
-      - name: Run Tests
-        run: npm run cucumber
+       - name: Run Cucumber tests
+        run: docker-compose up test-runner
+        continue-on-error: true
 
-      - name: Shutdown Docker Compose
+      - name: Display logs for debugging (if needed)
+        if: failure()
+        run: docker-compose logs
+
+      - name: Clean up Docker Compose
+        if: always()
         run: docker-compose down
+
+      - name: Post test summary
+        if: failure()
+        run: echo "Cucumber tests failed" && exit 1
